name: Sync dependency lock files

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup venv
        run: |
          uv venv
      - name: Check uv.lock is in-sync with pyproject.toml
        run: |
          uv lock --locked
      - name: Sync dependencies
        run: |
          uv export -o pylock.toml
          uv export --no-dev -o requirements.txt
          uv export --only-dev -o requirements_dev.txt
      - name: Git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Git diff
        run: |
          git diff HEAD || true
      - name: Git add
        run: |
          git add .
      - name: Git commit & push
        run: |
          git diff-index --quiet HEAD || ( git commit --amend --no-edit && git push --force-with-lease )
