name: Python unittest

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == true)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup venv
        run: |
          uv venv
      - name: Install dependencies
        run: |
          uv pip sync pylock.toml
          uv pip install -e .[dev]
      - name: Analysing the code with Python unittest
        run: |
          uv run python -m unittest $(git ls-files 'cog/tests/*.py')
          uv run python -m unittest $(git ls-files 'tests/unittest/*.py')
